# Generated by Django 3.2.6 on 2021-08-10 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerFullName', models.CharField(blank=True, max_length=250, null=True)),
                ('customerPhoneNumber', models.CharField(blank=True, max_length=10, null=True)),
                ('customerAddress', models.TextField(blank=True, null=True)),
                ('customerPincode', models.CharField(blank=True, max_length=6, null=True)),
                ('customerEmailId', models.CharField(blank=True, max_length=250, null=True)),
                ('tax', models.FloatField(default=0)),
                ('discount', models.FloatField(default=0)),
                ('taxAmount', models.FloatField(default=0)),
                ('discountAmount', models.FloatField(default=0)),
                ('subTotal', models.FloatField(default=0)),
                ('grandTotal', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=1000)),
                ('quantity', models.FloatField()),
                ('price', models.FloatField()),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.invoice')),
            ],
        ),
    ]
