# Generated by Django 3.2.6 on 2021-08-11 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_invoice_timestamp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InvoiceItems',
            new_name='InvoiceItem',
        ),
    ]
